repos:
  - repo: https://github.com/python/black
    rev: 23.10.1
    hooks:
      - id: black
        args: ["--line-length", "120", "--preview"]
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
        args: ["--profile", "black", "--filter-files"]
